import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#pd.set_option('display.max_rows',None)
df=pd.read_csv("HXPC13_DI_v3_11-13-2019 - Copy.csv")
data=df.groupby(['course_id','final_cc_cname_DI'])
data=data.size().reset_index(name='count')
cs50d=data[data['course_id']=='HarvardX/CS50x/2012']
countries=cs50d['final_cc_cname_DI'].tolist()
cs50cnt=cs50d['count'].tolist()
plt.bar(countries,cs50cnt,.6)
plt.xticks(rotation=90,fontsize=7)
plt.xlabel('regions')
plt.ylabel('number of students')
plt.title("number of students from each country in cs50")
plt.legend()
plt.show()
cb22xd=data[data['course_id']=='HarvardX/CB22x/2013_Spring']
countries=cb22xd['final_cc_cname_DI'].tolist()
cb22xcnt=cb22xd['count'].tolist()
plt.bar(countries,cb22xcnt,.6)
plt.xticks(rotation=90,fontsize=7)
plt.xlabel('regions')
plt.ylabel('number of students')
plt.title("number of students from each country in cb22")
plt.legend()
plt.show()
er22d=data[data['course_id']=='HarvardX/ER22x/2013_Spring']
countries=er22d['final_cc_cname_DI'].tolist()
er22cnt=er22d['count'].tolist()
plt.bar(countries,er22cnt,.6)
plt.xticks(rotation=90,fontsize=7)
plt.xlabel('regions')
plt.ylabel('number of students')
plt.title("number of students from each country in er22")
plt.legend()
plt.show()
ph207d=data[data['course_id']=='HarvardX/PH207x/2012_Fall']
countries=ph207d['final_cc_cname_DI'].tolist()
ph207cnt=ph207d['count'].tolist()
plt.bar(countries,ph207cnt,.6)
plt.xticks(rotation=90,fontsize=7)
plt.xlabel('regions')
plt.ylabel('number of students')
plt.title("number of students from each country in ph207")
plt.legend()
plt.show()
ph278d=data[data['course_id']=='HarvardX/PH278x/2013_Spring']
countries=ph278d['final_cc_cname_DI'].tolist()
ph278cnt=ph278d['count'].tolist()
plt.bar(countries,ph278cnt,.6)
plt.xticks(rotation=90,fontsize=7)
plt.xlabel('regions')
plt.ylabel('number of students')
plt.title("number of students from each country in ph278")
plt.legend()
plt.show()